### ISSUE TITLE
Issue stating Plone 5.1 after installing ftw.contacts

### ISSUE THREAD

**Issue by okhaledosama** [4teamwork/ftw.contacts#75]
Hi guys,

I am trying to install ftw.contacts on Plone 5.1.  buildout went fine, but Plone did not start and gave me the following error, given that I am on windows 8 and starting Plone in foreground

```python
E:\Plone\zinstance\bin>plonectl fg
instance: 2019-10-27 21:35:35 INFO ZServer HTTP server started at Sun Oct 27 21:
35:35 2019
        Hostname: Osama
        Port: 8080
Traceback (most recent call last):
  File "E:\Plone\zinstance\parts\instance\bin\interpreter-script.py", line 315,
in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\Startup\run.p
y", line 76, in <module>
    run()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\Startup\run.p
y", line 22, in run
    starter.prepare()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\Startup\__ini
t__.py", line 92, in prepare
    self.startZope()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\Startup\__ini
t__.py", line 268, in startZope
    Zope2.startup()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\__init__.py",
 line 47, in startup
    _startup()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\App\startup.p
y", line 120, in startup
    load_zcml()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\App\startup.p
y", line 52, in load_zcml
    load_site()
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\Zope2\App\zcml.py",
 line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 649, in file
    include(context, name, package)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "E:\Python27\Lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\config.py", line 558, in end
    self.stack.pop().finish()
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "e:\plone\buildout-cache\eggs\zope2-2.13.27-py2.7.egg\OFS\metaconfigure.p
y", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "E:\Python27\Lib\xml\sax\xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "E:\Python27\Lib\xml\sax\expatreader.py", line 384, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\config.py", line 558, in end
    self.stack.pop().finish()
  File "e:\plone\buildout-cache\eggs\zope.configuration-3.7.4-py2.7.egg\zope\con
figuration\config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "e:\plone\buildout-cache\eggs\z3c.autoinclude-0.3.8-py2.7.egg\z3c\autoinc
lude\zcml.py", line 101, in includePluginsDirective
    info = PluginFinder(dotted_name).includableInfo(zcml_to_look_for)
  File "e:\plone\buildout-cache\eggs\z3c.autoinclude-0.3.8-py2.7.egg\z3c\autoinc
lude\plugin.py", line 18, in includableInfo
    groups = zcml_to_include(plugin_dottedname, zcml_to_look_for)
  File "e:\plone\buildout-cache\eggs\z3c.autoinclude-0.3.8-py2.7.egg\z3c\autoinc
lude\plugin.py", line 36, in zcml_to_include
    filename = resource_filename(dotted_name, zcmlgroup)
  File "e:\plone\python-2.7\lib\site-packages\pkg_resources\__init__.py", line 1
144, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "e:\plone\python-2.7\lib\site-packages\pkg_resources\__init__.py", line 3
61, in get_provider
    __import__(moduleOrReq)
  File "e:\plone\buildout-cache\eggs\ftw.upgrade-2.13.0-py2.7.egg\ftw\upgrade\__
init__.py", line 5, in <module>
    from ftw.upgrade.step import UpgradeStep
  File "e:\plone\buildout-cache\eggs\ftw.upgrade-2.13.0-py2.7.egg\ftw\upgrade\st
ep.py", line 8, in <module>
    from ftw.upgrade.utils import log_silencer
  File "e:\plone\buildout-cache\eggs\ftw.upgrade-2.13.0-py2.7.egg\ftw\upgrade\ut
ils.py", line 5, in <module>
    from path import Path
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "E:\Plone\zinstance
\parts\instance\etc\site.zcml", line 12.2-12.39
    ZopeXMLConfigurationError: File "e:\plone\buildout-cache\eggs\products.cmfpl
one-5.1.5-py2.7.egg\products\CMFPlone\meta.zcml", line 37.4-41.10
    SyntaxError: invalid syntax (__init__.py, line 1266)
```

**Comment by jone** [comment]
The exception says that `from path import Path` is failing because there is an error in the `__init__.py` of `path`. This is part of the `path.py` python package.

I suspect that your `path.py`-Version is not compatible with your Python version.
You seem to be running Python 2.7.
Which version of `path.py` is installed? You can inspect your `bin/instance` or `bin/plonectl` to find out.

Be aware that [Python 2.7 support was dropped in `path.py==12.0.1`](https://github.com/jaraco/path.py/blob/master/CHANGES.rst#1201), so you should install a `path.py` version between `6.2` and `11.5.2`.

You can pin the version in the `[versions]` section of your buildout configuration.

**Comment by okhaledosama** [comment]
Thanks Jone for your reply,

It is indeed version 12.0.1, but it is picked during the buildout after adding fw.contacts to buildout.cfg

E:\Plone\zinstance\bin>e:\Plone\Python-2.7\Scripts\buildout.exe -c ..\buildout.c
fg
Uninstalling zopepy.
Uninstalling instance.
Unused options for buildout: 'backups-dir'.
Installing instance.
Getting distribution for 'ftw.contacts'.
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '._*' found anywhere in distribut
ion
Got ftw.contacts 1.9.0.
Getting distribution for 'ftw.upgrade'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '._*' found anywhere in distribut
ion
warning: no previously-included files matching '*.mo' found anywhere in distribu
tion
Got ftw.upgrade 2.13.0.
Getting distribution for 'ftw.autofeature'.
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '._*' found anywhere in distribut
ion
Got ftw.autofeature 1.1.0.
Getting distribution for 'ftw.zipexport'.
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '._*' found anywhere in distribut
ion
warning: no previously-included files matching '*.mo' found anywhere in distribu
tion
Got ftw.zipexport 1.6.4.
Generated script 'E:\\Plone\\zinstance\\bin\\instance'.
Generated interpreter 'E:\\Plone\\zinstance\\parts\\instance\\bin\\interpreter'.

Updating repozo.
Installing zopepy.
Generated interpreter 'E:\\Plone\\zinstance\\bin\\zopepy'.
Updating unifiedinstaller.
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
chardet = 3.0.4
configparser = 4.0.2
ftw.contacts = 1.9.0
idna = 2.6
importlib-metadata = 0.23
lepl = 5.1.3
path.py = 12.0.1
plone.app.jquery = 1.11.2
zipp = 0.6.0
zope.app.file = 3.6.1

# Required by:
# ftw.upgrade==2.13.0
argcomplete = 1.10.0

# Required by:
# ftw.contacts==1.9.0
collective.dexteritytextindexer = 2.3.0

# Required by:
# importlib-metadata==0.23
contextlib2 = 0.6.0.post1

# Required by:
# ftw.contacts==1.9.0
ftw.autofeature = 1.1.0

# Required by:
# ftw.contacts==1.9.0
ftw.upgrade = 2.13.0

# Required by:
# ftw.contacts==1.9.0
ftw.zipexport = 1.6.4

# Required by:
# ftw.upgrade==2.13.0
inflection = 0.3.1

# Required by:
# zipp==0.6.0
more-itertools = 7.2.0

# Required by:
# importlib-metadata==0.23
pathlib2 = 2.3.5

# Required by:
# ftw.zipexport==1.6.4
rfc6266 = 0.0.4

# Required by:
# pathlib2==2.3.5
scandir = 1.10.0

# Required by:
# ftw.upgrade==2.13.0
tarjan = 0.2.3.2

# Required by:
# ftw.contacts==1.9.0
z3c.schema = 1.1.0

I will try to pick an older version and will test again.  will keep you updated

**Comment by okhaledosama** [comment]
Thanks mate,  I pinned the version to 11.5.2 and Plone is up now

**Comment by jone** [comment]
Cool 🎉 👍 You're welcome 😉
